### PR TITLE
Updated: Added current key price rate and full inventory alert.

### PR DESCRIPTION
**Pull request by idinium96**
https://i.imgur.com/vRdwpjk.png

### CODE REVIEW

**Comment by Nicklason** [comment]
I feel like it shows too much information at once. I would rather add a command that gives you the key prices.

**Comment by idinium96** [comment]
> I feel like it shows too much information at once. I would rather add a command that gives you the key prices.

Ok, but if possible, please apply it to app\utils\offer\summarize.js only. 😉

**Comment by Nicklason** [comment]
Please don't add more commits to your pull request if  they don't  have anything to do with what it was originally about. If you have something else you would like implemented then make a second pull request.

**Comment by idinium96** [comment]
> Please don't add more commits to your pull request if they don't have anything to do with what it was originally about. If you have something else you would like implemented then make a second pull request.

Noted. I am sorry about that. Thank you for info. 👌

**Comment by danocmx** [comment]
Maybe only adding this info when necessery. Like when bot uses metal when no keys are found and uses metal instead of keys.

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/pull/176

**Comment by Nicklason** [comment]
Create an issue or a new pull request with the inventory full alert

**Pull request closed without merging**
