### PR TITLE
Look

### PR DESCRIPTION
**Pull request by AethezxD**
} else if (command == 'name' && Automatic.isOwner(steamID64)) {
        
			    Automatic.message(steamID64, 'Setting new name.');
			    let profileName = message.substr(message.toLowerCase().indexOf('name') + 5);

			    if (profileName == '') {
				Automatic.message(steamID64, 'You forgot to add a name. Here\'s an example: "!name Mr Bot"');
				return;
			    } else {
				message = command.replace("name ", "");
			    var someOtherprofileName = profileName
			    client.setPersona(1, someOtherprofileName);
			    Automatic.message(steamID64, "New name = " + someOtherprofileName);
			    }
			} else {
			Automatic.message(steamID64, 'I don\'t know what you mean, please type "!help" for all my commands!');
		}
	});
}

### CODE REVIEW

**Comment by ZeusJunior** [comment]
Mate what

**Comment by AethezxD** [comment]
waht

**Comment by ZeusJunior** [comment]
y u steal >:(

**Comment by AethezxD** [comment]
no

**Comment by Nicklason** [comment]
#20

**Pull request closed without merging**
