### PR TITLE
Dupe checks 🔥

### PR DESCRIPTION
**Pull request by Nicklason**
Adds dupe checks to the bot.

- Enable dupe checks by setting `ENABLE_DUPE_CHECK` to `true`. Default is `false`.
- Minimum price for dupe check can be setting `MINIMUM_KEYS_DUPE_CHECK` to any amount in keys, both whole numbers and decimals. Default is `0`.
- Decline offers that contain any duped items by setting `DECLINE_DUPES` to `true`. Default is `false`.
- If a dupe check fails then for received offers the offer will be skipped and a notification will be sent to the admins for them to review the offer, for sending offers the bot will stop and say that it failed to check for dupes.

If the bot fails to make a dupe check when creating an offer then the bot should tell the user to try and send an offer instead, that way an admin will be able to review the offer and accept / decline it.

How dupe checks work:

1. The bot attempts to get the history page of an item on backpack.tf. It will use the current assetid that the item has. If it fails then the dupe check will fail.
2. If backpack.tf knows about the item using the current assetid then the dupe check is done and the result will depend on if backpack.tf says it is duped or not.
3. If backpack.tf does not know about the item, then the bot will load the inventory using the TF2 GetPlayerItems API that backpack.tf also used to load inventories. The bot will load the inventory and find the original id. If the API does not give a good response, or the item could not be found in the inventory, then the dupe check fails.
4. The bot now has the original id and can then try and get the item history from backpack.tf using that. If it fails then we can conclude that backpack.tf doesn't know about the item, meaning that we don't know if the item is duped or not. The dupe check will fail. If backpack.tf does know about the item, then the dupe check is done.

### CODE REVIEW

**Comment by Nicklason** [comment]
I need to make the bot do dupe checks when sending offers and then it is done.

**Comment by Gobot1234** [comment]
420 is the haha number

**Comment by Nicklason** [comment]
I have added dupe checks for sending offers now

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/pull/420

**Pull request merged**
