### PR TITLE
better elevated quality check

### PR DESCRIPTION
**Pull request by SeizedThoughts**
previously, getElevatedQuality got only decorated weapons and war paints that were strange using the description 'Strange Stat Clock Attached'.

this has been fixed using the type attribute to determine if the item is a strange cosmetic and the getQuality method to check if the item is a strange cosmetic

### CODE REVIEW

**Comment by Nicklason** [comment]
Hello, please stop opening and cllosing the issue.

I am not sure why you get a build error and I don't really have time to check it out, but you are free to figure it out yourself, then I'll happily approve the pull request :)

**Comment by SeizedThoughts** [comment]
i'm sorry about the opening and closing of the request. i didn't know that you were being notified. this is the first time i've made a pull request from my repo to another, so i have never encountered the checks.

i will continue to look into the issue with building.

**Comment by SeizedThoughts** [comment]
the tests have passed. i have learned that i am not a fan of the format that eslint uses. :p

still, the code is ready to be reviewed!

thank you for being patient with me. :)

**Comment by SeizedThoughts** [comment]
a slight change was made to account for items such as this: https://steamcommunity.com/id/BobbyTheFemble/inventory/#440_2_6867229753
where there's no strange part attached description and the item is not a cosmetic.

**Pull request closed without merging**
