### PR TITLE
Added rate command and made bot always value keys using sell price

### PR DESCRIPTION
**Pull request by Nicklason**
- Removed function `getKeyPrices` and replaced it with `getKeyPrice` inside `app/prices.js`
  - The bot will use the sell price for keys as their value
- Save only key price in polldata instead of both buy and sell for keys
- Added rate command used to see what the bot values keys at

### CODE REVIEW

**Comment by ZeusJunior** [comment]
Would this not cause possible errors with trading? Since you're using the same price for both buy and sell

**Comment by Nicklason** [comment]
> Would this not cause possible errors with trading? Since you're using the same price for both buy and sell

I have thought about it but it should not be a problem. The reason to why we need to use one key price is so that 1 key is always worth the same when trading items. Say someone offers you 1 key for your item priced  at 1 key, then those two values will actually be `1 * key buy price` and `1 * key sell price`, meaning that the values don't match.

For trading keys it will use the buy and sell price, but when trading items it will use the sell price on both sides.

**Comment by Nicklason** [comment]
When looking at the code I might have broken key banking, so I need to fix that.

**Comment by Nicklason** [comment]
> When looking at the code I might have broken key banking, so I need to fix that.

Fixed it: https://github.com/Nicklason/tf2-automatic/commit/5667cc22b180ae10ad666bc8499b6dd985ca1ac7

**Pull request merged**
