### PR TITLE
Review offers

### PR DESCRIPTION
**Pull request by Nicklason**
Resolves: https://github.com/Nicklason/tf2-automatic/issues/174

### CODE REVIEW

**Comment by idinium96** [comment]
I've tried it, so far so good.
Suggestions:
1. Send notification to the trade partner that his/her trade is pending for review by the owner so that he/she knows that they need to wait. 
2. It might be nice if GIFT also can be reviewed.
3. Send notification to ADMINS if there is any trade that needs to be reviewed? maybe like every # hours?
[review1](https://user-images.githubusercontent.com/47635037/75982356-6b7af080-5f21-11ea-814b-a6367a562ec2.PNG)
[review2](https://user-images.githubusercontent.com/47635037/75982360-6cac1d80-5f21-11ea-9265-5fee4f655581.PNG)

Thanks.

**Comment by Nicklason** [comment]
> I've tried it, so far so good.
> Suggestions:
> 
> 1. Send notification to the trade partner that his/her trade is pending for review by the owner so that he/she knows that they need to wait.
> 2. It might be nice if GIFT also can be reviewed.
> 3. Send notification to ADMINS if there is any trade that needs to be reviewed? maybe like every # hours?
> 
> [review1](https://user-images.githubusercontent.com/47635037/75982356-6b7af080-5f21-11ea-814b-a6367a562ec2.PNG)
> [review2](https://user-images.githubusercontent.com/47635037/75982360-6cac1d80-5f21-11ea-9265-5fee4f655581.PNG)
> 
> Thanks.

Already made an issue for notifying https://github.com/Nicklason/tf2-automatic/issues/362

**Comment by Nicklason** [comment]
Gifts won't be reviewed because it has a setting for accepting gifts. But I did make review for escrow offers because you might want to accept them anyway.

**Comment by idinium96** [comment]
> Already made an issue for notifying #362

Yeah, it should be implemented (for me... need to wait for others review).

> Gifts won't be reviewed because it has a setting for accepting gifts. But I did make review for escrow offers because you might want to accept them anyway.

I see... then `"ALLOW_ESCROW":` in `.env` and `ecosystem.json` should be set `true`?

**Comment by idinium96** [comment]
@Nicklason, I think it's best to check for bans/escrow before skipping the trade offer because of OVERSTOCKED/INVALID_VALUE/INVALID_ITEM.
[escrow](https://user-images.githubusercontent.com/47635037/76059361-9d3f9600-5fb9-11ea-89e1-61e4ecba1767.PNG)
[escrow2](https://user-images.githubusercontent.com/47635037/76059412-bba59180-5fb9-11ea-8b62-9eb416b17bdd.PNG)

**Comment by Nicklason** [comment]
> @Nicklason, I think it's best to check for bans/escrow before skipping the trade offer for review because of OVERSTOCKED/INVALID_ITEM/INVALID_VALUE case.
> [escrow](https://user-images.githubusercontent.com/47635037/76059361-9d3f9600-5fb9-11ea-89e1-61e4ecba1767.PNG)
> [escrow2](https://user-images.githubusercontent.com/47635037/76059412-bba59180-5fb9-11ea-8b62-9eb416b17bdd.PNG)

very nice that you spotted that, maybe just have the bot check for escrow and bans when it first receives the offer, if it will be in escrow then just decline it instead of skipping it

**Comment by idinium96** [comment]
Yes, agree with that, unless the user set "ALLOW_ESCROW" is true, then it will skip to review an escrow offer.

**Comment by idinium96** [comment]
I don't think this is overstocked. I've set the intent for all craft weapons to bank with max=100, and the other things (like craft hats/tools) to sell with max=10 (which perhaps if someone bought some weapon from the bot, they also give some sweets or extras, just like in screenshot.)

Is it if we set intent=sell, the bot does not want the items to be in the bot's inventory, even though the bot does not have a single one of it?

[overstock](https://user-images.githubusercontent.com/47635037/76146810-0d8d0b00-60d1-11ea-86ea-19f7b7ae0d60.PNG)
[overstock2](https://user-images.githubusercontent.com/47635037/76146397-5e9b0000-60cd-11ea-8fcb-36738755374e.PNG)

**Comment by idinium96** [comment]
@Nicklason, it is better than for **INVALID_VALUE** offer to just decline the trade and notify the trade partner. No need to be reviewed.

**Comment by idinium96** [comment]
> very nice that you spotted that, maybe just have the bot check for escrow and bans when it first receives the offer, if it will be in escrow then just decline it instead of skipping it

Will this works? 
[commit](https://github.com/idinium96/tf2-automatic/commit/dbb04be670b9919e44cae7a1940d6ed34aff867d)

**Comment by idinium96** [comment]
will this be implemented soon to the master @Nicklason?

**Comment by idinium96** [comment]
Maybe if add some feature like add parameter `all=true` in `!accepttrade` or `!declinetrade` command.
tradess

**Comment by idinium96** [comment]
Here I have all possible cases:

The only item in pricelist is:
Battle-Worn Robot Money Furnace, with
min=0,
max=1
buy.metal=0.55
sell.metal=1

1. INVALID_ITEMS (our side)
[Invalid-item-our-side](https://user-images.githubusercontent.com/47635037/78965027-703d5080-7b2e-11ea-887e-0c49cb5a67a4.PNG)

2. INVALID_ITEMS (their side - he/she must offer correct value + item that is not in pricelist)
[Invalid-item-their-side](https://user-images.githubusercontent.com/47635037/78965160-d1fdba80-7b2e-11ea-9de9-f8cb6dc12741.PNG)

3. INVALID_VALUE (our side)
[invalid-value-our-side](https://user-images.githubusercontent.com/47635037/78965307-420c4080-7b2f-11ea-90ae-8a4a9994b869.PNG)

4. INVALID_VALUE (their side)
[invalid-value-their-side](https://user-images.githubusercontent.com/47635037/78965448-afb86c80-7b2f-11ea-8554-1498faafeb31.PNG)

5. OVERSTOCKED (when partner offers overstocked item with correct value)
[overstocked-our-side](https://user-images.githubusercontent.com/47635037/78965500-d1b1ef00-7b2f-11ea-8ba9-a436a96d34a8.PNG)

6. INVALID_ITEMS, INVALID_ITEMS (if partner want to offer and take items that are not in pricelist - both side)
[invalid-item-invalid-item-both-side](https://user-images.githubusercontent.com/47635037/78965612-16d62100-7b30-11ea-9852-b09d75eac29a.PNG)

7. INVALID_ITEMS, INVALID_VALUE (their side)
[invalid-items-invalid-value-their-side](https://user-images.githubusercontent.com/47635037/78965717-64eb2480-7b30-11ea-876a-e7f22f55c16d.PNG)

8. INVALID_ITEMS, INVALID_VALUE (our side)
[invalid-items-invalid-value-our-side](https://user-images.githubusercontent.com/47635037/78965963-273acb80-7b31-11ea-9070-ab531a7c8b8e.PNG)

9. OVERSTOCKED, INVALID_VALUE (when partner offers an overstocked item and taking an incorrect value) 
[overstocked-invalid-value](https://user-images.githubusercontent.com/47635037/78966158-a4fed700-7b31-11ea-9565-e2ce1e1aa7e6.PNG)

10. INVALID_ITEMS, OVERSTOCKED, INVALID_VALUE (when partner offers an overstocked item and taking an incorrect value and an item not in pricelist)
[invalid-items-overstocked-invalid-value](https://user-images.githubusercontent.com/47635037/78966678-112e0a80-7b33-11ea-8883-669c22219e82.PNG)

11. INVALID_ITEMS, OVERSTOCKED, INVALID_ITEMS, INVALID_VALUE (when partner offers an overstocked item and an item that is not in pricelist and taking an incorrect value and item not in pricelist)
[invalid-items-overstocked-invalid-items-invalid-value](https://user-images.githubusercontent.com/47635037/78967077-03c55000-7b34-11ea-9e11-6490a8cd6cd8.PNG)

12. INVALID_ITEMS, INVALID_ITEMS, INVALID_VALUE (this might not happens. The trade partner is offering and taking the same item with both side having an item that is not in pricelist)
[invalid-items-invalid-items-invalid-value](https://user-images.githubusercontent.com/47635037/78967359-d62cd680-7b34-11ea-9045-7c4963e53c97.PNG)

**Comment by idinium96** [comment]
This might worth mentioning here, that item overpay is still marked as OVERSTOCKED.
I add Reinforced Robot Bomb Stabilizer with intent=sell, and this item is still not in the bot's inventory.
[item-overpay-marked-overstockted](https://user-images.githubusercontent.com/47635037/78968471-4177a800-7b37-11ea-93a8-0fd41fe1e0fe.PNG)

**Comment by DexGunner** [comment]
Got an error when sending `!trades` command

**Pull request merged**
