### PR TITLE
Change accept and decline commands for reviewing

### PR DESCRIPTION
**Pull request by DexGunner**
Changed accept and decline commands for reviewing

### CODE REVIEW

**Comment by idinium96** [comment]
Wait.. you have to change something else

**Comment by DexGunner** [comment]
> Wait.. you have to change something else

Change what?

**Comment by idinium96** [comment]
And also you're not following on how to contribute actually.
https://github.com/Nicklason/tf2-automatic/blob/master/.github/contributing.md

**Comment by idinium96** [comment]
Basically this:
https://github.com/Nicklason/tf2-automatic/blob/af52e6d376f25082aa2262780eec7e0d34344293/src/classes/Commands.ts#L1510
and this:
https://github.com/Nicklason/tf2-automatic/blob/af52e6d376f25082aa2262780eec7e0d34344293/src/classes/Commands.ts#L1560

**Comment by DexGunner** [comment]
> Basically this:
> https://github.com/Nicklason/tf2-automatic/blob/af52e6d376f25082aa2262780eec7e0d34344293/src/classes/Commands.ts#L1510
> 
> 
> and this:
> https://github.com/Nicklason/tf2-automatic/blob/af52e6d376f25082aa2262780eec7e0d34344293/src/classes/Commands.ts#L1560

I left it to Nick, as commands work without these changes, and Nick uses these names, and he decides how it is more convenient

**Comment by idinium96** [comment]
No, it won't work unless you change it.

**Comment by DexGunner** [comment]
> No, it won't work unless you change it.

I already tested it
image

**Comment by Nicklason** [comment]
@idinium96 i don't see why it shouldn't work, all he did was change the name of the commands

**Comment by idinium96** [comment]
🤔 if you said like that, then idk. I thought the one at _processMessage_ should match with the function name.

**Comment by Nicklason** [comment]
> 🤔 if you said like that, then idk. I thought the one at _processMessage_ should match with the function name.

yes, but it will still work

**Comment by idinium96** [comment]
ah.. alright @Nicklason 👌

**Comment by Nicklason** [comment]
if you want this merged then you need contributors to approve it

**Comment by DexGunner** [comment]
> if you want this merged then you need contributors to approve it

Well, what should I do so that they approve?

**Comment by Nicklason** [comment]
> > if you want this merged then you need contributors to approve it
> 
> Well, what should I do so that they approve?

make contributors agree with you, then they will approve

**Comment by Zeckatz** [comment]
I like the command name as it is. `!accept`/`!decline` doesn't explain what your accepting/declining.

**Comment by Nicklason** [comment]
> I like the command name as it is. `!accept`/`!decline` doesn't explain what your accepting/declining.

Yeah me too. Say we add a new command for accepting friend requests or whatever. Then there will be "accept" and "acceptfriend". Making the command be just "accept" doesn't tell much about the command.

I'll close the PR for this reason.

**Pull request closed without merging**
